# Generated by Django 2.1.7 on 2019-02-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(max_length=12)),
                ('end_time', models.FloatField(max_length=12)),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('video_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
        migrations.RemoveField(
            model_name='word',
            name='segment_start_time',
        ),
        migrations.AlterField(
            model_name='word',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video'),
        ),
        migrations.AddField(
            model_name='captionsegment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video'),
        ),
        migrations.AddField(
            model_name='word',
            name='start_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='captions.CaptionSegment'),
            preserve_default=False,
        ),
    ]
