# Generated by Django 2.1.7 on 2019-02-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0004_auto_20190220_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='captionsegment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video', to_field='video_id'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video', to_field='video_id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captions.Video', to_field='video_id'),
        ),
    ]
